version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      
      - run:
          name: Run unit Tests
          command: python -m pytest ./APItest/APItesting.py --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - run:
          name: Run Tests
          command: 
                  python -m coverage run -m pytest ./APItest/APItesting.py
      - run:
          name: Run Tests2
          command:
                  python -m coverage report
      - run:
          name: Run Tests3
          command:
                  pythob -m coverage html  # open htmlcov/index.html in a browser
      - store_artifacts:
          path: htmlcov


workflows:
  main:
    jobs:
      - build-and-test
